version: "3"
services:
  kb_indexer:
    image: qcdis/kb-indexer:latest
    networks:
      - kb-indexer-network
    environment:
      - DATA_DIR=$DATA_DIR
      - ELASTICSEARCH_USERNAME=$ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KAGGLE_USERNAME=$KAGGLE_USERNAME
      - KAGGLE_KEY=$KAGGLE_KEY
      - GITHUB_API_TOKEN=$GITHUB_API_TOKEN
  elastic_backend:
    image: elasticsearch:8.12.1
    networks:
      - kb-indexer-network
    environment:
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_USER=$ELASTICSEARCH_USERNAME
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${PWD}/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    deploy:
      resources:
        limits:
          memory: 1GB
    depends_on:
      - fixsysctl
  fixsysctl: # Some fix because limits are too low by default
    restart: "no"
    privileged: true
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25m
    image: centos:7
    command: "sysctl -w vm.max_map_count=262144"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - kb-indexer-network
  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=http://elastic_backend:9200'
    restart: always
    ports:
    - "9114:9114"
    networks:
      - kb-indexer-network
networks:
  kb-indexer-network: {}

